{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOoc9E7/WT49wVeP22i+OsL",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Huseyin3737/veri-yapilari-odev-arama-siralama/blob/main/main.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import time\n",
        "from typing import List\n",
        "\n",
        "# ==========================================\n",
        "# PERFORMANS ÖLÇÜMÜ (DECORATOR)\n",
        "# ==========================================\n",
        "def zaman_olcer(fonksiyon):\n",
        "    \"\"\"\n",
        "    Algoritmaların çalışma süresini milisaniye cinsinden ölçen özel dekoratör.\n",
        "    Optimizasyon ve zaman karmaşıklığı analizini somutlaştırmak için kullanılmıştır.\n",
        "    \"\"\"\n",
        "    def sarmalayici(*args, **kwargs):\n",
        "        baslangic = time.perf_counter()\n",
        "        sonuc = fonksiyon(*args, **kwargs)\n",
        "        bitis = time.perf_counter()\n",
        "        gecen_sure = (bitis - baslangic) * 1000 # Milisaniyeye çevir\n",
        "        print(f\"[{fonksiyon.__name__.upper()}] çalışma süresi: {gecen_sure:.4f} ms\")\n",
        "        return sonuc\n",
        "    return sarmalayici\n",
        "\n",
        "# ==========================================\n",
        "# ALGORİTMA MİMARİSİ (OOP)\n",
        "# ==========================================\n",
        "class VeriYapilariAlgoritmalar:\n",
        "    \"\"\"\n",
        "    Arama ve sıralama işlemlerini kapsülleyen sınıf yapısı.\n",
        "    \"\"\"\n",
        "\n",
        "    @staticmethod\n",
        "    def linear_search(veri_seti: List[int], hedef: int) -> int:\n",
        "        for indeks, deger in enumerate(veri_seti):\n",
        "            if deger == hedef:\n",
        "                return indeks\n",
        "        return -1\n",
        "\n",
        "    @staticmethod\n",
        "    def binary_search(sirali_veri: List[int], hedef: int) -> int:\n",
        "        sol, sag = 0, len(sirali_veri) - 1\n",
        "        while sol <= sag:\n",
        "            # (sol + sag) // 2 yerine taşma (overflow) riskini önleyen güvenli hesaplama\n",
        "            orta = sol + (sag - sol) // 2\n",
        "\n",
        "            if sirali_veri[orta] == hedef:\n",
        "                return orta\n",
        "            elif sirali_veri[orta] < hedef:\n",
        "                sol = orta + 1\n",
        "            else:\n",
        "                sag = orta - 1\n",
        "        return -1\n",
        "\n",
        "    @staticmethod\n",
        "    @zaman_olcer\n",
        "    def bubble_sort(veri_seti: List[int]) -> List[int]:\n",
        "        dizi = veri_seti.copy()\n",
        "        n = len(dizi)\n",
        "        for i in range(n):\n",
        "            degisim_oldu_mu = False\n",
        "            for j in range(0, n - i - 1):\n",
        "                if dizi[j] > dizi[j + 1]:\n",
        "                    dizi[j], dizi[j + 1] = dizi[j + 1], dizi[j]\n",
        "                    degisim_oldu_mu = True\n",
        "            # Optimizasyon: Eğer hiç yer değişikliği olmadıysa dizi zaten sıralıdır, döngüyü kır.\n",
        "            if not degisim_oldu_mu:\n",
        "                break\n",
        "        return dizi\n",
        "\n",
        "    @staticmethod\n",
        "    @zaman_olcer\n",
        "    def selection_sort(veri_seti: List[int]) -> List[int]:\n",
        "        dizi = veri_seti.copy()\n",
        "        n = len(dizi)\n",
        "        for i in range(n):\n",
        "            min_indeks = i\n",
        "            for j in range(i + 1, n):\n",
        "                if dizi[j] < dizi[min_indeks]:\n",
        "                    min_indeks = j\n",
        "            dizi[i], dizi[min_indeks] = dizi[min_indeks], dizi[i]\n",
        "        return dizi\n",
        "\n",
        "    @staticmethod\n",
        "    @zaman_olcer\n",
        "    def insertion_sort(veri_seti: List[int]) -> List[int]:\n",
        "        dizi = veri_seti.copy()\n",
        "        for i in range(1, len(dizi)):\n",
        "            anahtar = dizi[i]\n",
        "            j = i - 1\n",
        "            while j >= 0 and anahtar < dizi[j]:\n",
        "                dizi[j + 1] = dizi[j]\n",
        "                j -= 1\n",
        "            dizi[j + 1] = anahtar\n",
        "        return dizi\n",
        "\n",
        "    @staticmethod\n",
        "    @zaman_olcer\n",
        "    def merge_sort(veri_seti: List[int]) -> List[int]:\n",
        "        # Merge Sort recursive (özyinelemeli) olduğu için zaman ölçümü ana fonksiyonda yapılır\n",
        "        def _ayir_ve_birlestir(dizi: List[int]) -> List[int]:\n",
        "            if len(dizi) <= 1:\n",
        "                return dizi\n",
        "\n",
        "            orta = len(dizi) // 2\n",
        "            sol_yari = _ayir_ve_birlestir(dizi[:orta])\n",
        "            sag_yari = _ayir_ve_birlestir(dizi[orta:])\n",
        "\n",
        "            birlestirilmis = []\n",
        "            i = j = 0\n",
        "\n",
        "            while i < len(sol_yari) and j < len(sag_yari):\n",
        "                if sol_yari[i] < sag_yari[j]:\n",
        "                    birlestirilmis.append(sol_yari[i])\n",
        "                    i += 1\n",
        "                else:\n",
        "                    birlestirilmis.append(sag_yari[j])\n",
        "                    j += 1\n",
        "\n",
        "            birlestirilmis.extend(sol_yari[i:])\n",
        "            birlestirilmis.extend(sag_yari[j:])\n",
        "            return birlestirilmis\n",
        "\n",
        "        return _ayir_ve_birlestir(veri_seti.copy())\n",
        "\n",
        "# ==========================================\n",
        "# ÇALIŞTIRMA VE TEST ALANI\n",
        "# ==========================================\n",
        "if __name__ == \"__main__\":\n",
        "    # Test Verisi\n",
        "    orijinal_veri = [88, 14, 53, 27, 91, 32, 6, 19, 74, 45]\n",
        "    print(f\"--- Orijinal Veri Seti: {orijinal_veri} ---\\n\")\n",
        "\n",
        "    # Sınıfı Başlat\n",
        "    algoritma = VeriYapilariAlgoritmalar()\n",
        "\n",
        "    # --- SIRALAMA TESTLERİ ---\n",
        "    print(\">>> SIRALAMA ALGORİTMALARI PERFORMANS TESTİ <<<\")\n",
        "    bubble_sirali = algoritma.bubble_sort(orijinal_veri)\n",
        "    selection_sirali = algoritma.selection_sort(orijinal_veri)\n",
        "    insertion_sirali = algoritma.insertion_sort(orijinal_veri)\n",
        "    merge_sirali = algoritma.merge_sort(orijinal_veri)\n",
        "\n",
        "    print(f\"\\nSıralanmış Çıktı Örneği: {merge_sirali}\\n\")\n",
        "\n",
        "    # --- ARAMA TESTLERİ ---\n",
        "    aranan_sayi = 53\n",
        "    print(\">>> ARAMA ALGORİTMALARI TESTİ <<<\")\n",
        "\n",
        "    linear_indeks = algoritma.linear_search(orijinal_veri, aranan_sayi)\n",
        "    print(f\"Linear Search -> '{aranan_sayi}' sayısı orijinal dizide {linear_indeks}. indekste bulundu.\")\n",
        "\n",
        "    binary_indeks = algoritma.binary_search(merge_sirali, aranan_sayi)\n",
        "    print(f\"Binary Search -> '{aranan_sayi}' sayısı sıralı dizide {binary_indeks}. indekste bulundu.\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "hChoZ0DO8Mvf",
        "outputId": "f7667a92-462b-4114-8b8f-e61e3b8e4e88"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "--- Orijinal Veri Seti: [88, 14, 53, 27, 91, 32, 6, 19, 74, 45] ---\n",
            "\n",
            ">>> SIRALAMA ALGORİTMALARI PERFORMANS TESTİ <<<\n",
            "[BUBBLE_SORT] çalışma süresi: 0.0156 ms\n",
            "[SELECTION_SORT] çalışma süresi: 0.0074 ms\n",
            "[INSERTION_SORT] çalışma süresi: 0.0062 ms\n",
            "[MERGE_SORT] çalışma süresi: 0.0231 ms\n",
            "\n",
            "Sıralanmış Çıktı Örneği: [6, 14, 19, 27, 32, 45, 53, 74, 88, 91]\n",
            "\n",
            ">>> ARAMA ALGORİTMALARI TESTİ <<<\n",
            "Linear Search -> '53' sayısı orijinal dizide 2. indekste bulundu.\n",
            "Binary Search -> '53' sayısı sıralı dizide 6. indekste bulundu.\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "Y7ZdK1Lb-NfO"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}